name: '🤖 Gemini Run'

on:
  workflow_call:
    inputs:
      prompt:
        type: 'string'
        required: true
        description: 'The prompt or command to execute'
      extensions:
        type: 'string'
        required: false
        description: 'JSON array of extensions to install'
        default: '[]'
      additional_context:
        type: 'string'
        required: false
        description: 'Any additional context'
      gemini_model:
        type: 'string'
        required: false
        default: 'gemini-2.5-flash'
      settings:
        type: 'string'
        required: false
        description: 'JSON string written to ~/.gemini/settings.json'
        default: '{}'
      gemini_debug:
        type: 'string'
        required: false
        default: 'false'

defaults:
  run:
    shell: 'bash'

jobs:
  run:
    runs-on: 'ubuntu-latest'
    timeout-minutes: 10
    permissions:
      contents: 'read'
      id-token: 'write'
      pull-requests: 'write'
      issues: 'write'
    steps:
      - name: 'Checkout repository'
        uses: 'actions/checkout@v4'
        with:
          persist-credentials: 'false'
          fetch-depth: 0

      - name: 'Run Gemini CLI'
        uses: 'google-github-actions/run-gemini-cli@v0.1.22'
        env:
          GEMINI_CLI_TRUST_WORKSPACE: 'true'
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN || github.token }}'
          GEMINI_API_KEY: '${{ secrets.GEMINI_API_KEY }}'
        with:
          gemini_api_key: '${{ secrets.GEMINI_API_KEY }}'
          gemini_model: '${{ inputs.gemini_model }}'
          prompt: '${{ inputs.prompt }}'
          settings: '${{ inputs.settings }}'
          extensions: '${{ inputs.extensions }}'
          workflow_name: '${{ github.workflow }}'
          gemini_debug: '${{ inputs.gemini_debug }}'
