name: 'Gemini Review'

on:
  workflow_call:
    inputs:
      additional_context:
        type: 'string'
        description: 'Any additional context from the request'
        required: false
        
concurrency:
  group: '${{ github.workflow }}-review-${{ github.event_name }}-${{ github.event.pull_request.number || github.event.issue.number }}'
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

defaults:
  run:
    shell: 'bash'

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Load Gemini Configurations for PR Review
        id: config
        working-directory: .gemini/ci/pr-review
        run: |
          {
            echo "settings<<EOF"
            cat settings.json
            echo ""
            echo "EOF"

            echo "prompt<<EOF"
            echo "/pr-code-review"
            echo ""
            cat PROMPT.md
            echo ""
            echo "EOF"

            echo "extensions<<EOF"
            cat extensions.json
            echo ""
            echo "EOF"
          } >> "$GITHUB_OUTPUT"
      
      - name: Run Gemini CLI for PR Review
        uses: google-github-actions/run-gemini-cli@v0.1.22
        env:
          GITHUB_TOKEN: ${{ github.token }}
          ISSUE_TITLE: '${{ github.event.pull_request.title || github.event.issue.title }}'
          ISSUE_BODY: '${{ github.event.pull_request.body || github.event.issue.body }}'
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          REPOSITORY: ${{ github.repository }}
          PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number || github.event.issue.number }}
          ADDITIONAL_CONTEXT: '${{ inputs.additional_context }}'
        with:
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
          use_gemini_code_assist: ${{ vars.GOOGLE_GENAI_USE_GCA == 'true' }}
          use_vertex_ai: ${{ vars.GOOGLE_GENAI_USE_VERTEXAI == 'true' }}
          workflow_name: 'gemini-review'
          gemini_cli_version: 'latest'
          gemini_model: 'gemini-2.5-flash'
          # Explicitly set the PR number to handle `issue_comment` triggers (which GitHub treats as issues, not PRs)
          github_pr_number: '${{ github.event.pull_request.number }}'
          prompt: ${{ steps.config.outputs.prompt }}
          settings: ${{ steps.config.outputs.settings }}
          extensions: ${{ steps.config.outputs.extensions }}
          gemini_debug: '${{ fromJSON(vars.GEMINI_DEBUG || vars.ACTIONS_STEP_DEBUG || false) }}'